### ISSUE TITLE
You are not allowed to transition swapchain images without first acquiring them.

### ISSUE THREAD

**Issue by ratchetfreak** [thirddegree/HatchitGraphics#46]
https://github.com/thirddegree/HatchitGraphics/blob/95258f9477a4d65aa68b2ed20ce1003bfbe7ee13/source/vulkan/ht_vkswapchain.cpp#L806

This will do a layout transition on the swapchain images before you have acquired them. [This is not allowed:](https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#_wsi_swapchain)

> Use of a presentable image must occur only after the image is returned by `vkAcquireNextImageKHR`, and before it is presented by `vkQueuePresentKHR`. **This includes transitioning the image layout and rendering commands.**

Instead you can always transition [from UNDEFINED pre-render](https://github.com/thirddegree/HatchitGraphics/blob/b3cffa79494dfe1065c97a67806cfcebe20ac56a/source/vulkan/ht_vkswapchain.cpp#L382). Which implies that you don't care about the data in the image.

[See here](http://stackoverflow.com/q/37524032/731620) for more info

**Comment by Honeybunch** [comment]
I removed that image transition and the "Post Present" command buffer will always transition from an Undefined image layout now. As seen in e8d2823435b865b63e1ba852c4fd43c86510ebf0

**Comment by ratchetfreak** [comment]
looks good.
